/** Auto-generated by scripts/write-frontend-config.js — do not edit on Vercel. */
window.SA_CONFIG = {
  "API_BASE": "http://localhost:8000/api",
  "WS_URL": "ws://localhost:8000/ws/telemetry",
  "HEALTH_URL": "http://localhost:8000/health"
};
